### PR TITLE
allow install on php 7.0 and 7.1

### PR DESCRIPTION
**Pull request by TavoNiievez**
allow install on php 7.0 and 7.1

### CODE REVIEW

**Comment by SoftCreatR** [comment]
Hello @TavoNiievez,

right now, I am working on backports for PHP 7.0 and 7.1. I would still like to drop support for PHP < 7.2, that's why I aim to create separate branches for these versions. See https://github.com/SoftCreatR/JSONPath/tree/php-56 for example.

**Comment by TavoNiievez** [comment]
@SoftCreatR thanks you

**Comment by SoftCreatR** [comment]
FYI: The `main` branch supports PHP 7.1 now. For PHP 5.6 & 7.0, there are separate branches.

**Comment by TavoNiievez** [comment]
my only remaining question is: does this code allow `dev-php-70` to be installed on higher versions of php? or just 7.0.x
https://github.com/SoftCreatR/JSONPath/blob/46ed9811b37e0fff900a88376ffb27fec8583ddc/composer.json#L19-L22

**Comment by SoftCreatR** [comment]
Just PHP 7.0.

**Pull request closed without merging**
