### PR TITLE
[Bug-68] added support for length on array

### LINKED ISSUE #68: $.length doesn't work
Using the following as an example input:
```
[
   1,
   3,
   5
]
```

The following path `$.length` should return `[3]`
Actual result: `[]`

The above is based on the site https://jsonpath.com/ working as described with the example.

### PR DESCRIPTION
**Pull request by Lukazar**
+ added token value check for length only if named key doesn't exist
+ updated test case to show it working
+ bonus: fixed test case for working length checks on script expressions

Resolves #68

### CODE REVIEW

**Comment by SoftCreatR** [comment]
I'm unsure, if this function should return an array containing the length, or just the int value. I'm aware of the fact, that most implementations that support this function will return `[X]`, but for me, this is somewhat unexpected. What do you think?

**Comment by Lukazar** [comment]
That's a fair critique.  However - it seems every query / filter regardless of the type of expression returns an array.  Its probably better to maintain that consistent return type (and keep with the other libraries to maintain some amount of consensus).  Also - its just personal preference, but I've never been a huge fan of mixed return types unless its something like <scalar>|null and enforceable with `...function (): ?array...`

**Comment by SoftCreatR** [comment]
I'll think about it. For some reason, I'd prefer not to return the result of this call as an array.

**Comment by SoftCreatR** [comment]
Thank you very much.

**Pull request merged**
