### PR TITLE
Fix php81 deprecated warnings

### PR DESCRIPTION
**Pull request by pbojan**
# 🔀 Pull Request

## What does this PR do?
Fix deprecated warnings for PHP 8.1:

```
Deprecated: Return type of Flow\JSONPath\JSONPath::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
Exception:
ErrorException: Deprecated: Return type of Flow\JSONPath\JSONPath::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /www/foe/libs/external/softcreatr/jsonpath/src/JSONPath.php:271
```

## Test Plan
No automated test plan only manual testing done.

## Related PRs and Issues
No related PRs or Issues

### CODE REVIEW

**Comment by SoftCreatR** [comment]
Thank you. However, this will be a breaking change, since the mixed keyword doesn't exist in older PHP versions.

**Comment by pbojan** [comment]
That is very true. Any plans from your side to migrate to at least PHP 8.0? I could potentially help out but I don't know how much work that would be as I am not aware of all the side-effects that could create.

**Comment by SoftCreatR** [comment]
PHP 8.0+ is officially supported and covered by our automatic tests (see https://github.com/SoftCreatR/JSONPath/blob/main/.github/workflows/Test.yml#L24).

However, if there's any need, I'll release a new version for sure.

**Comment by andrew-demb** [comment]
How about just adding #[\ReturnTypeWillChange] attribute?

**Comment by SoftCreatR** [comment]
That's the current plan.

**Comment by SoftCreatR** [comment]
That's also a breaking change, because it doesn't work with older PHP versions.

**Comment by pbojan** [comment]
Should I update the PR to remove the mixed and replace it with the Attribute then?

**Comment by SoftCreatR** [comment]
No. A new version (for PHP 8.0+) is required here.

**Comment by pbojan** [comment]
Actually I think this works because for previous PHP versions attributes are regarded as comments:

```
PHP versions prior to 8.0 parses the attribute syntax as a code comment, and does not cause any syntax errors. Adding #[\ReturnTypeWillChange] attribute to a class method does not cause any issues, but omits the deprecation notice in PHP 8.1.
```

https://php.watch/versions/8.1/ReturnTypeWillChange

**Comment by SoftCreatR** [comment]
Yeah, my bad. I forgot to put that on a separate line, so all tests failed locally :)

But I'm already working on updates.

**Comment by SoftCreatR** [comment]
Resolved via 37f949dfe5e5d9236da2dd5453b8b22c633a6d1d

**Comment by pbojan** [comment]
@SoftCreatR thank you for the quick fix!

**Comment by SoftCreatR** [comment]
Please let me know, if the provided solution works for you.

**Comment by gigimaor** [comment]
Hello
Continuing to the above, I have the same issue, but no solution is present in the code.

`Error message
Deprecated function: Return type of Flow\JSONPath\JSONPath::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in include() (line 29 of /builds/web-team/ua-arop/vendor/softcreatr/jsonpath/src/JSONPath.php).`

This new attribute that supports php:^81 is required `#[\ReturnTypeWillChange]` or fixing the compatibility issue described in the error.

Please advise.

**Comment by SoftCreatR** [comment]
Are you using the latest version 0.8.2?

**Comment by gigimaor** [comment]
we are using PHP 8.1.2

**Comment by gigimaor** [comment]
I update the version, and the solution presents itself

**Comment by SoftCreatR** [comment]
Means?

**Comment by gigimaor** [comment]
Updating to version 0.8.2 has fixed the issue.  Thanks

**Pull request closed without merging**
