### PR TITLE
Idea of multi index search

### PR DESCRIPTION
**Pull request by Darknez07**
This is the idea proposed within the code, I have commented the code for the indexing and added a regex for the multi index matching thanks for review in advance.

### CODE REVIEW

**Comment by SoftCreatR** [comment]
Hey,

thank you for your PR. Looks like I've accidentally disabled the issues section.

As of now, this PR could not be merged. At least, because of the syntax error in line 32. But I'll leave this open for further improvements (and tests!)

**Comment by Darknez07** [comment]
Forgot a semicolon

**Comment by Darknez07** [comment]
@SoftCreatR  Are you thinking of merging this anytime soon?

**Comment by SoftCreatR** [comment]
Tbh, that's way too incomplete to be merged. However, this PR counts towards your Hacktoberfest goal (just in case that you are participating).

**Comment by Darknez07** [comment]
@SoftCreatR  Actually I already fulfilled it, and that is genuine suggestion

**Comment by Darknez07** [comment]
@SoftCreatR  guide me to completion

**Comment by SoftCreatR** [comment]
Well, the only code change here is the addition of a regular expression. There's currently no use for this regex and no test. It's currently just a proposal.

**Pull request closed without merging**
