### PR TITLE
key union selector, fix #22

### LINKED ISSUE #22: Union With Keys
Test Data:

```json
{
  "key": "value",
  "another": "entry"
}
```

Selector:

```
$['key','another']
```

Result:

```diff
--- Expected
+++ Actual
@@ @@
-'["value","entry"]'
+'[]'
```

More information: https://cburgmer.github.io/json-path-comparison/results/union_with_keys

### PR DESCRIPTION
**Pull request by SG5**

### CODE REVIEW

**Comment by SoftCreatR** [comment]
This also

resolves #15
resolves #23 
resolves #24 
resolves #25

**Comment by SG5** [comment]
@SoftCreatR could you add label `hacktoberfest-accepted` for this PR?

**Comment by SoftCreatR** [comment]
Sure, but is this required? From what I can remember, PRs count towards the goal, if they either have the label OR if they have been merged.

**Comment by SG5** [comment]
Thanks
This year they changed rules to prevent PR spam. A repo OR a PR should have label to be counted

**Comment by SoftCreatR** [comment]
Ah, yeah. I've removed the hacktoberfest Tag from the Repo. That might be the problem.

**Pull request merged**
